# Generated by Django 4.0.3 on 2022-03-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_article_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avartar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/%Y/%m'),
        ),
    ]
